Added text editor within VisualGit
kblincoe/VisualGit_SE701_3 pull request #62
Opened 2018-03-13 03:55 UTC by cli727

- The panel that displays insertions/deletions of modified files now displays the file content and allows the content to be edited when 'Edit' is pressed
- 'Save' and 'Cancel' buttons are created in a new div. Allows saving or cancel the editing of the modified file
- A new script 'file.ts' is added to deal with file reading and saving, and the corresponding behavior when 'Save' and 'Cancel' buttons are pressed; This file is also added in 'index.html'
- 'router.ts' has been modified to deal with hiding/displaying the 'Save' and 'Cancel' buttons when their parent panel is hidden/displayed
- 'index.html' has been modified to use 'file.ts'
- 'style.css' has been modified to style 'Save' and 'Cancel' buttons
- Closes issue #32

2018-03-13 05:32 UTC, EmilyYVChan commented on index.html
> +             //opn(repoFullPath + "/" + content);
Is this meant to stay commented out?

2018-03-13 05:34 UTC, cli727 commented on index.html
> +             //opn(repoFullPath + "/" + content);
Yeah it won't affect the functionality. But I will remove it for good practice sake : )

2018-03-13 23:04 UTC, EmilyYVChan requested changes
I found a bug where the user is able to edit the text in the file although the user is not in 'Edit' mode.
To reproduce this failure:

Attempt to edit text in a file. But instead of saving the changes, click cancel.
Click on the file to open the diff panel.
Type directly into the diff panel. This is where the bug is.
@cli727 kindly amend.

2018-03-14 00:52 UTC, cli727 commented
@EmilyYVChan Thanks, that was indeed a bug. The html element was simply forgotten to be set non-editable after user cancels the operation. The bug should be fixed with the latest commit and please kindly review again.

2018-03-15 01:19 UTC, EmilyYVChan approved these changes
Have tested the bug that Chen fixed. Looks good now.

2018-03-15 01:19 UTC, EmilyYVChan commented
@softeng-701 ready for merge :)

2018-03-15 02:16 UTC, softeng-701 commented
@EmilyYVChan please squash your commits

2018-03-15 04:08 UTC, EmilyYVChan commented
@cli727 I think it's better if you do the squashing since you are the primary owner of this issue.

2018-03-15 04:42 UTC, cli727 commented
@softeng-701 Changes from upstream are pulled and merged; all commits squashed; ready for merge

2018-03-15 07:53 UTC, merged